name: Run G9 Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/3 * * * *'

jobs:
  g9_botml_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Increase VM swap space
        run: |
          sudo swapoff -a
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install required packages
        run: |
          pip install telebot pymongo aiohttp

      - name: Check DNS Configuration
        run: cat /etc/resolv.conf

      - name: binary by @G9
        run: chmod +x G9
        
      - name: Run main.py
        run: python3 main.py

      - name: Clean up swap
        if: always()
        run: |
          sudo swapoff /swapfile
          sudo rm /swapfile
